#
# Mesos
# https://open.mesosphere.com/downloads/mesos/#apache-mesos-0.25.0
#
---
- name: Install Mesos
  yum: pkg=mesos state=latest update_cache=yes


- name: Configure Mesos ZK settings
  lineinfile: dest=/etc/mesos/zk create=yes line="zk://{{zk_host1}}:2181,{{zk_host2}}:2181,{{zk_host3}}:2181/mesos"

- name: Configure Mesos Master quorum
  lineinfile: dest=/etc/mesos-master/quorum create=yes line="{{mesos_quorum}}"
  when: mesos_type == "master"

- name: Configure Mesos containerizers
  lineinfile: dest=/etc/mesos-slave/containerizers create=yes line="docker,mesos"
  when: mesos_type == "slave"


- name: Enable Mesos Master
  service: name=mesos-master state=started enabled=yes
  when: mesos_type == "master"

- name: Disable Mesos Slave
  service: name=mesos-slave state=stopped enabled=no
  when: mesos_type == "master"


- name: Enable Mesos Master
  service: name=mesos-master state=stopped enabled=no
  when: mesos_type == "slave"

- name: Disable Mesos Slave
  service: name=mesos-slave state=started enabled=yes
  when: mesos_type == "slave"
