#
# Deploy an app to Marathon and update Bamboo's rules
#
# Marathon docs: https://mesosphere.github.io/marathon/docs/rest-api.html
# Bamboo docs:   https://github.com/QubitProducts/bamboo
#
---
- name: Update Marathon manifest
  template: src={{manifest}}.j2 dest=/tmp/{{manifest}}
  tag: marathon

- name: Uninstall Marathon task
  command: "curl -X DELETE http://{{marathon_host}}:8080/v2/apps/{{app_id}}"
  tag: marathon

# See https://mesosphere.github.io/marathon/docs/rest-api.html#post-/v2/apps for details
- name: Install Marathon task
  command: "curl -X POST http://{{marathon_host}}:8080/v2/apps -d @/tmp/{{manifest}} -H 'Content-type: application/json'"
  tag: marathon

- name: Clean up marathon manifest
  command: rm -f /tmp/{{manifest}}
  tag: marathon


- name: Add BamBoo rule
  command: "curl -i -X PUT -d '{"id":"{{app_id}}", "acl":"path_beg -i {{app_id}}"}' http://{{bamboo_host}}:8000/api/services/{{app_id}}"
  tag: bamboo
