#
# ElasticSearch and Kibana (from a docker container)
#
# See https://hub.docker.com/_/elasticsearch/
# See https://hub.docker.com/_/kibana/
#
# You shouldn't run ES in this way (at least until you move its data/logs dirs outside the container),
# so that is just an academical example which can be quickly deployed :)
#
---
- name: Install ElasticSeach
  shell: docker run -d --net=host --name elasticsearch elasticsearch

- name: Install Kibana
  shell: docker run -d --name kibana --link elasticsearch:elasticsearch -p 5601:5601 kibana
