#
# Bamboo and Haproxy install
#
# https://github.com/QubitProducts/bamboo/tree/master/ (see "builder" folder)
#
---
- name: Install HaProxy
  sudo: yes
  yum: pkg=haproxy state=present update_cache=yes
  tags: yum

#
# Building Bamboo package (manually)
#
# Unfortunately, there is no a repo with Bamboo package. So, you have to build it manually (see the commands below)
# and store it on your local machine before running this role.
#
# See Bamboo's home page for details: https://github.com/QubitProducts/bamboo/
#
# dnf install git golang ruby-devel gcc
# gem install fpm
#
# mkdir -p scr/github.com/QubitProducts/
# git clone https://github.com/QubitProducts/bamboo.git src/github.com/QubitProducts/bamboo
# cd src/github.com/QubitProducts/bamboo
#
# #go get github.com/tools/godep
# export GOPATH=`pwd`/../../../../:/usr/lib/golang
#
# go build bamboo.go
# ./builder/build.sh
#
# ls -al output
# ~bamboo_1.0.0-1_all.deb
# ~bamboo-1.0.0_1-1.noarch.rpm (if you need a RPM package, just update ./builder/build.sh script)
#
# cp output/bamboo-1.0.0_1-1.noarch.rpm /tmp
#
- name: Install Bamboo
  sudo: yes
  yum: pkg=/tmp/bamboo-1.0.0_1-1.noarch.rpm state=present
  tags: yum

- name: Configure Bamboo (copy config)
  template:
    src: production.json.j2
    dest: /var/bamboo/production.json

- name: Enable Bamboo server
  service: name=bamboo-server state=restarted enabled=yes
