---
- hosts: nodes
  remote_user: vagrant
  become: yes
  become_method: sudo
  roles:
    - { role: "docker", tags: "zookeeper" }
    - { role: "mesos", mesos_type: "slave", tags: "mesos" }
    - { role: "mesos-dns", tags: "dns" }
